apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospeda-frontend
  labels:
    app: hospeda-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hospeda-frontend
  template:
    metadata:
      labels:
        app: hospeda-frontend
    spec:
      containers:
      - name: hospeda-frontend
        image: deyvid14/hospeda_frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: api_url
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
